runtime: java11
entrypoint: java -Dserver.port=$PORT -jar ngo-nabarun-app-0.0.3.jar
env: standard
instance_class: B2
basic_scaling:
  max_instances: 1
  idle_timeout: 15m
handlers:
  - url: /.*
    script: this field is required, but ignored
env_variables:
  ENVIRONMENT: STAGE
