runtime: java17
instance_class: F1
automatic_scaling:
  min_instances: 0
  max_instances: 2
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.75
env_variables:
  ENVIRONMENT: $ENVIRONMENT
  DOPPLER_PROJECT_NAME: $DOPPLER_PROJECT_NAME
  DOPPLER_SERVICE_TOKEN: $DOPPLER_SERVICE_TOKEN
  LOG_LEVEL: $LOG_LEVEL
  
