name: Deploy Workflow

on: 
  workflow_dispatch
jobs:
  test:
    # This job runs on pull_request events
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Add steps for testing your java app
      - name: Run tests
        run: mvn clean install -DskipTests

  build_and_deploy:
    # This job runs on push events, specifically after PRs are merged into main
    # needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17' 
          distribution: 'adopt'

      - name: Set environment variables from secrets
        run: |
          echo "DOPPLER_PROJECT_NAME=${{ secrets.DOPPLER_PROJECT_NAME }}" >> $GITHUB_ENV
          echo "DOPPLER_SERVICE_TOKEN=${{ secrets.DOPPLER_SERVICE_TOKEN }}" >> $GITHUB_ENV

      - name: Setup Google Cloud CLI
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: 'auto' # Automatically generate a version ID
          deliverables: ngo-nabarun-app/target/ngo-nabarun-app-0.0.3.jar # Update this to the path of your built JAR
