name: Deploy Workflow
on: 
  workflow_dispatch
  
jobs:
  build_and_deploy:
    # This job runs on push events, specifically after PRs are merged into main
    # needs: test
    #if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17' 
          distribution: 'adopt'

      - name: Setup Google Cloud CLI
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Build with Maven
        run: mvn clean package
        
      - name: Set Env Var
        uses: ikuanyshbekov/app-yaml-env-compiler@v1.0
        with:
          path: "app.yaml"
        env:
         ENVIRONMENT: ${{ env.APP_ENV }} 
         DOPPLER_PROJECT_NAME: ${{ env.DOPPLER_PROJECT_NAME }} 
         DOPPLER_SERVICE_TOKEN: ${{ secrets.DOPPLER_SERVICE_TOKEN }}  
         LOG_LEVEL: ${{ secrets.LOG_LEVEL }} 
         
      - name: Deploy to Google App Engine
        uses: google-github-actions/deploy-appengine@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: true
          version: auto # Automatically generate a version ID
          deliverables: ngo-nabarun-app/target/ngo-nabarun-app-0.0.3.jar
          flags: '--appyaml=app.yaml'
